default: &default
  host: <%= ENV['TESSERACT_PORT_5000_TCP_ADDR'] %>
  port: <%= ENV['TESSERACT_PORT_5000_TCP_PORT'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default